# This is a basic workflow to help you get started with Actions

name: Publish to Alexa Skill Dev Environment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install expect
      run: |
        sudo apt-get install expect
        which expect
        
    - name: Install ASK CLI
      run: |
        npm install -g ask-cli
        mkdir ~/.aws
        echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials
        mkdir ~/.ask
        echo "${{ secrets.ASK_CONFIG }}" > ~/.ask/cli_config

    - name: Set up ASK CLI
      run: |
        sudo chmod +x ./ask-setup.exp
        ./ask-setup.exp ${{ secrets.SKILL_ID }}

    - name: Push to master branch in Alexa Git Repository
      run: |
        cd step-to-jeff-alexa
        git config credential.helper store
        echo https://andrewhlu:${{ github.token }}@github.com >> ~/.git-credentials
        git remote add github $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -f
        git pull github master --ff-only
        git push origin master
        git checkout dev
        git push origin dev
